[package]
name = "chapter-6"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "list6-1"
path = "src/list6-1.rs"

[[bin]]
name = "list6-2"
path = "src/list6-2.rs"

[[bin]]
name = "list6-4"
path = "src/list6-4.rs"

[[bin]]
name = "list6-5"
path = "src/list6-5.rs"

[[bin]]
name = "list6-6"
path = "src/list6-6.rs"

[[bin]]
name = "list6-7"
path = "src/list6-7.rs"

[[bin]]
name = "list6-9"
path = "src/list6-9.rs"

[dependencies]
piston_window = "0.117"
piston2d-graphics = "0.39"
rand = "0.8"
